"""
railui/cli/build.py

``railui build`` — compile the project to a production bundle and generate
deployment configuration files for Railway/Docker.
"""
from __future__ import annotations

import importlib.util
import os
import sys


# ---------------------------------------------------------------------------
# Deployment file templates
# ---------------------------------------------------------------------------
_RAILWAY_TOML = """\
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn railui.backend.server:create_app --factory --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
"""

_PROCFILE = "web: uvicorn railui.backend.server:create_app --factory --host 0.0.0.0 --port $PORT\n"

_REQUIREMENTS_HINT = """\
# Auto-generated by railui build — add project-specific dependencies below.
fastapi>=0.115
uvicorn[standard]>=0.30
watchdog>=4.0
"""


def _write_if_missing(path: str, content: str) -> None:
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        # Use simple ASCII logging since it's just scaffolding
        print(f"  \033[32mcreated\033[0m {os.path.relpath(path).replace(os.sep, '/')}")


import subprocess
import time

def _format_size(size: int) -> str:
    """Format bytes to kB with 2 decimal places."""
    return f"{size / 1024:.2f} kB"

def run(project_dir: str) -> int:
    """Execute a production build and generate deployment files."""
    main_py = os.path.join(project_dir, "main.py")
    if not os.path.exists(main_py):
        print(f"\033[31m[railui] Error: no main.py found in {project_dir}\033[0m")
        return 1

    print(f"\n\033[36mrailui\033[0m building for production...\n")
    start_time = time.monotonic()

    # 1. Run the build in a clean subprocess to capture output
    result = subprocess.run(
        [sys.executable, main_py],
        cwd=project_dir,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"\033[31mBuild failed:\033[0m")
        print(result.stderr)
        return 1

    # 2. Generate deployment artefacts
    _write_if_missing(os.path.join(project_dir, "railway.toml"), _RAILWAY_TOML)
    _write_if_missing(os.path.join(project_dir, "Procfile"), _PROCFILE)
    _write_if_missing(os.path.join(project_dir, "requirements.txt"), _REQUIREMENTS_HINT)

    # 3. Print the beautiful summary of generated files
    dist_dir = os.path.join(project_dir, "dist")
    print(f"\n\033[32m✓\033[0m \033[2mbuild complete in {time.monotonic() - start_time:.2f}s\033[0m\n")
    
    if os.path.exists(dist_dir):
        files = []
        for root, _, filenames in os.walk(dist_dir):
            for f in filenames:
                fp = os.path.join(root, f)
                rel = os.path.relpath(fp, project_dir)
                size = os.stat(fp).st_size
                files.append((rel, size))
                
        # Sort by size (largest last) for better visual flow
        files.sort(key=lambda x: x[1])
        
        for rel_path, size in files:
            color = "\033[36m" if rel_path.endswith(".js") else "\033[35m" if rel_path.endswith(".css") else "\033[2m"
            # Format: right-aligned size, colored path
            print(f"  {_format_size(size):>10}  {color}{rel_path.replace(os.sep, '/')}\033[0m")
            
    print("\n\033[32mReady for deployment! (\033[1mrailway up\033[0m)\n")
    return 0
